#!/bin/bash
PIDASH_PAGES="$HOME/.pidash-pages"
PIDASH_LOG="$HOME/.pidash.log"
PIDASH_ERROR="$HOME/.pidash-error.log"
while true; do
  echo "Starting $PIDASH"
  pidash $PIDASH_PAGES 1> $PIDASH_LOG 2> $PIDASH_ERROR &
  PID=$!
  echo "Got PID $PID"
  echo "Waiting for changes to $PIDASH_PAGES"
  /usr/bin/inotifywait $PIDASH_PAGES -e modify
  echo "Killing pidash..."
  /bin/kill $PID
done
